name: music_player_simp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  http: ^1.1.0
  just_audio: ^0.9.35
  # Functional programming thingies
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3

  logger: ^2.0.1
  fluttertoast: ^8.2.2
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/